Mappings:
  RegionMap:
    us-east-1:
      WebsiteEndpoint: s3-website-us-east-1.amazonaws.com
    us-west-2:
      WebsiteEndpoint: s3-website-us-west-2.amazonaws.com
    us-west-1:
      WebsiteEndpoint: s3-website-us-west-1.amazonaws.com
    eu-west-1:
      WebsiteEndpoint: s3-website-eu-west-1.amazonaws.com
    eu-central-1:
      WebsiteEndpoint: s3-website.eu-central-1.amazonaws.com
    ap-southeast-1:
      WebsiteEndpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-northeast-1:
      WebsiteEndpoint: s3-website-ap-northeast-1.amazonaws.com
    ap-southeast-2:
      WebsiteEndpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-2:
      WebsiteEndpoint: s3-website.ap-northeast-2.amazonaws.com
    sa-east-1:
      WebsiteEndpoint: s3-website-sa-east-1.amazonaws.co

Parameters:
  ApplicationName:
    Type: String
    Default: ServerlessLink
    Description: The name of the serverlesss application
  DomainName:
    Type: String
    Default: ${opt:domain}
    Description: The name of the domain for the serverless application
  PartitionKey:
    Type: String
    Default: LinkId
    Description: The name of the main parition key
  StageName:
    Type: String
    Default: ${self:custom.stageName}

Resources:
  WebsiteBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName:
        Ref: DomainName
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: DomainName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Join: ["", ["arn:aws:s3:::", Ref: DomainName, "/*"]]

  # Certificate for cloud front distribution.
  # This must be approved by admin for the CF template to be successful
  AcmDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainName:
        Ref: DomainName

  WebsiteCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - Ref: DomainName
        Comment: Created by µServerless
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: WebsiteBucket
          ViewerProtocolPolicy: redirect-to-https
        Enabled: 'true'
        Origins:
        - CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
          DomainName:
            Fn::Join: [".", [Ref: WebsiteBucket, Fn::FindInMap: [RegionMap, Ref: AWS::Region, WebsiteEndpoint]]]
          Id: WebsiteBucket
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn:
            Ref: AcmDomainCertificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName:
          Ref: PartitionKey
        AttributeType: S

      KeySchema:
      - AttributeName:
          Ref: PartitionKey
        KeyType: HASH

      TimeToLiveSpecification:
        AttributeName: ExpirationTime
        Enabled: true

  AcmApiDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainName:
        Fn::Join: [".", ["m", Ref: DomainName]]

  ApiGatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      # Use if you want it to create a cloudfront distribution
      # HostedZoneId: Z2FDTNDATAQYW2
      CertificateArn:
        Ref: AcmApiDomainCertificate
      EndpointConfiguration:
        Types:
          - EDGE

      # Use if you want to create a regional endpoint
      # HostedZoneId: Z1UJRXOUMOOFQ8
#      RegionalCertificateArn:
#        Ref: AcmApiDomainCertificate
#      EndpointConfiguration:
#        Types:
#        - REGIONAL
      DomainName:
        Fn::Join: [".", ["m", Ref: DomainName]]

  DomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: ""
      Stage:
        Ref: StageName
      DomainName:
        Ref: ApiGatewayDomain
      RestApiId:
       Ref: ApiGatewayRestApi

  WebsiteDomainRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Serverless Link webisite domain record set
      HostedZoneName:
        Fn::Join: ["", [Ref: DomainName, "."]]
      RecordSets:
        - AliasTarget:
            DNSName:
              Fn::GetAtt: [WebsiteCloudfrontDistribution, DomainName]
            HostedZoneId: Z2FDTNDATAQYW2  # This is the default hosted zone id for CloudFront
          Name:
            Ref: DomainName
          Type: A

  ApiDomainRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Serverless Link webisite domain record set
      HostedZoneName:
        Fn::Join: ["", [Ref: DomainName, "."]]
      RecordSets:
        - AliasTarget:
            DNSName:
              Fn::GetAtt: [ApiGatewayDomain, DistributionDomainName]
            HostedZoneId: Z2FDTNDATAQYW2  # This is the default hosted zone id for CloudFront
          Name:
            Fn::Join: [".", ["m", Ref: DomainName]]
          Type: A

Outputs:
  EventsJsonArchive:
    Value:
      Ref: DynamoDBTable

